name: merge-requests

on:
  pull_request:
    branches:
    - master

jobs:
  merge-requests:
    name: Merge Request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check
      uses: ./.github/actions/check
    - name: Build
      uses: ./.github/actions/build
